####################################################################################################
################ Config file for all the input parameters ##########################################
####################################################################################################


################## General Input [Days, Detector, Data Type, Energy Channels] #######################
general:
  dates: ['160310']
  detector: 'n1'
  data_type: 'ctime'
  echan_list: [3]
  min_bin_width: 30

################# Input for response precalculation [how many grid poits?] ##########################
response:
  Ngrid: 40000

####### Input for SAA mask precaluclation [time to exclude after SAA, delete short time intervals? ##
saa:
  time_after_saa: 50
  short_time_intervals: False
  nr_decays: 1

###### Input for geometry calculation [n time bins per day to calculate the geometry ################
geometry:
  n_bins_to_calculate: 800

##### Input for source Setup [use CR, use Earth, use CGB, point source list, fix earth, fix cgb #####
setup:
  use_saa: True
  use_constant: True
  use_cr: True
  use_earth: True
  use_cgb: True
  ps_list: ['CRAB']
  fix_ps: [True]
  fix_earth: True
  fix_cgb: True
  use_sun: False
  bgo_cr_approximation: True

################################ Bounds for the different sources ###################################
####### SAA: Amplitude and decay constant, CR: Constant and McIlwain normalization ##################
####### Point source: Amplitude, Earth/CGB fixec: Amplitude, Earth/CGB free: Amplitude, #############
############################ index1, index2 and break energy#########################################
bounds:
  saa_bound: [[1, 1e4], [1e-5, 1e-1]]
  cr_bound: [[1e-1, 1e2], [0.1, 1e2]]
  earth_fixed_bound: [[1e-3, 1]]
  cgb_fixed_bound: [[1e-2, 0.5]]
  earth_free_bound: [[1e-3, 1], [-8, -3], [1.1, 1.9], [20, 40]]
  cgb_free_bound: [[0.01, 0.5], [0.5, 1.7], [2.2, 3.1], [27, 40]]
  ps_fixed_bound: [[1e-4, 1]]
  ps_free_bound: [[1e-4, 1], [1.5, 2.5]]
  sun_bound: [[1e-2, 1e2], [0.5,4]]

gaussian_bounds:
  saa_bound: [[None, None], [None, None]]
  cr_bound: [[None, None], [None, None]]
  earth_fixed_bound: [[None, None]]
  cgb_fixed_bound: [[None, None]]
  earth_free_bound: [[None, None], [-5, 2], [1.72, 0.1], [None, None]]
  cgb_free_bound: [[None, None], [1.32, 0.1], [2.88, 0.15], [None, None]]
  ps_fixed_bound: [[None, None]]
  ps_free_bound: [[None, None], [2.1, 0.3]]
  sun_bound: [[None, None], [2., 1.]]

##################### Input for multinest sampler ###################################################
fit:
  method: 'multinest'
  multinest:
    num_live_points: 400
    constant_efficiency_mode: True

export:
  save_cov_matrix: False
  save_ppc: True
  save_unbinned: True

############################### Input for plotting ##################################################
### bin_width to bin the data, change_time from MET to seconds since midnight, show residuals? ######
### show data?, show grb trigger times? if yes at which time ('20:57:03.000' format) and what name? #
### show ppc?, xlim and ylim (as list e.g. [0,100]), legend outside of the plot? ####################
plot:
  bin_width: 30
  change_time: True
  show_residuals: False
  show_data: True
  plot_sources: True
  show_grb_trigger: True
  times_mark: []
  names_mark: []
  ppc: True
  xlim: None
  ylim: None
  legend_outside: False
