####################################################################################################
################ Config file for all the input parameters ##########################################
####################################################################################################


################## General Input [Days, Detector, Data Type, Energy Channels] #######################
general:
  dates:      ['130131']
  detectors:   ['n9'] #,'n6','na'] #,"na"]#,'n3','n4','n5','n8',"na"]
  data_type:  'ctime'
  echans: ["2","4"] #"15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30"]#["15-20","20-25","25-30"]
  min_bin_width: 30

################# Input for response precalculation [how many grid poits?] ##########################
response:
  Ngrid: 4000

####### Input for SAA mask precaluclation [time to exclude after SAA, delete short time intervals? ##
saa:
  time_after_saa: 100
  short_time_intervals: false
  nr_decays_per_exit: 1
  decay_at_day_start: true
  decay_per_detector: false
  decay_model: exponential

###### Input for geometry calculation [n time bins per day to calculate the geometry ################
geometry:
  n_bins_to_calculate: 800

##### Input for source Setup [use CR, use Earth, use CGB, point source list, fix earth, fix cgb #####
setup:
  use_saa:      true
  use_constant: true
  use_cr:       true
  use_earth:    true
  use_cgb:      true
  ps_list:

    # Give path to file of point sources that are all initalized in the same way (except position)
    #list:
    #  path: /home/bjorn/Documents/point_sources_all_54.dat
    #  fixed: true
    #  spectrum:
    #    bb:
    #      spectrum_type: bb
    #      blackbody_temp: 2
    #    pl:
    #      spectrum_type: pl
    #      powerlaw_index: 3

    auto_swift:
        flux_limit: 0.2
        free: []
        exclude: []
        time_variable: []

    #CRAB:
    #  fixed: false
    #  spectrum:
    #    pl:
    #      spectrum_type: pl
    #      powerlaw_index: 2

    #SCOX-1:
    #  fixed: false
    #  spectrum:
        #pl:
        #  spectrum_type: pl
        #  powerlaw_index: 2
    #    bb:
    #      spectrum_type: bb
    #      blackbody_temp: 2

  fix_earth:    true
  fix_cgb:      true
  use_sun:      false
  cr_approximation: BGO
  use_eff_area_correction: true

################################ Bounds for the different sources ###################################
####### SAA: Amplitude and decay constant, CR: Constant and McIlwain normalization ##################
####### Point source: Amplitude, Earth/CGB fixec: Amplitude, Earth/CGB free: Amplitude, #############
############################ index1, index2 and break energy#########################################
bounds:
  saa_bound:
    norm:   [1, 1.0e+4]
    decay:  [1.0e-5, 1.0e-1]
  cr_bound:
    const:  [1.0e-1, 1.0e+2]
    norm:   [0.1, 1.0e+2]
  earth_fixed_bound:
    norm:   [1.0e-3, 1]
  cgb_fixed_bound:
    norm:   [1.0e-2, 0.5]
  earth_free_bound:
    norm:   [1.0e-3, 1]
    alpha:  [-8, -3]
    beta:   [1.1, 1.9]
    Eb:     [20, 40]
  cgb_free_bound:
    norm:   [0.01, 0.5]
    alpha:  [0.5, 1.7]
    beta:   [2.2, 3.1]
    Eb:     [27, 40]
  ps_fixed_bound:
    pl:
      norm:   [1.0e-1, 100]
    bb:
      norm:   [1.0e-4, 100]
  ps_free_bound:
    pl:
      norm:   [1.0e-1, 100]
      index:  [1,3]
    bb:
      norm:   [1.0e-4, 100]
      temp:   [0,5]
  sun_bound:
    norm: [1.0e-2, 1.0e+2]
    index: [0.5,4]
  eff_area_correction: [0.8,1.2]

gaussian_bounds:
  saa_bound:
    norm:   [null, null]
    decay:  [null, null]
  cr_bound:
    const:  [null, null]
    norm:   [null, null]
  earth_fixed_bound:
    norm:   [null, null]
  cgb_fixed_bound:
    norm:   [null, null]
  earth_free_bound:
    norm:   [null, null]
    alpha:  [-5, 2]
    beta:   [1.72, 0.1]
    Eb:     [null, null]
  cgb_free_bound:
    norm:   [null, null]
    alpha:  [1.32, 0.1]
    beta:   [2.88, 0.15]
    Eb:     [null, null]
  ps_fixed_bound:
    pl:
      norm: [null, null]
    bb:
      norm:  [null, null]
  ps_free_bound:
    pl:
      norm: [null, null]
      index: [null, null]
    bb:
      norm: [null, null]
      temp: [null, null]
  sun_bound:
    norm:   [null, null]
    index:  [2., 1.]
  eff_area_correction: [1.0, 0.1]
##################### Input for fit method ##########################################################
fit:
  method: 'multinest'
  multinest:
    num_live_points: 400
    constant_efficiency_mode: true
  use_numba: false

##################### Input for Result Export  ######################################################
export:
  save_cov_matrix: false
  save_ppc: true
  save_unbinned: false

############################### Input for plotting ##################################################
### bin_width to bin the data, change_time from MET to seconds since midnight, show residuals? ######
### show data?, show grb trigger times? if yes at which time ('20:57:03.000' format) and what name? #
### show ppc?, xlim and ylim (as list e.g. [0,100]), legend outside of the plot? ####################
plot:
  bin_width:      30
  change_time:    true
  show_residuals: false
  show_data:      true
  plot_sources:   true
  show_grb_trigger: true
  times_mark:     []
  names_mark:     []
  ppc:            true
  xlim:           null
  ylim:           null
  legend_outside: false
