####################################################################################################
################ Config file for all the input parameters ##########################################
####################################################################################################


################## General Input [Days, Detector, Data Type, Energy Channels] #######################
general:
  dates:      ['160310']
  detectors:   ['n1']
  data_type:  'ctime'
  echans: ["2"]
  min_bin_width: 30

################# Input for response precalculation [how many grid poits?] ##########################
response:
  Ngrid: 40000

####### Input for SAA mask precaluclation [time to exclude after SAA, delete short time intervals? ##
saa:
  time_after_saa: 5000
  short_time_intervals: false
  nr_decays_per_exit: 2
  decay_at_day_start: true
  decay_per_detector: false
  decay_model: exponential

###### Input for geometry calculation [n time bins per day to calculate the geometry ################
geometry:
  n_bins_to_calculate: 800

##### Input for source Setup [use CR, use Earth, use CGB, point source list, fix earth, fix cgb #####
setup:
  use_saa:      false
  use_constant: true
  use_cr:       true
  use_earth:    true
  use_cgb:      true
  use_gc:       true

  ps_list:

    # Give path to file of point sources that are all initalized in the same way (except position)
    #list:
    #  path: ./point_sources.dat
    #  fixed: true
    #  spectrum:
    #    bb:
    #      spectrum_type: bb
    #      blackbody_temp: 2
    #    pl:
    #      spectrum_type: pl
    #      powerlaw_index: 3

    auto_swift:
        flux_limit: 0.1
        exclude: []
        free: [Crab, SCOX-1]

  fix_earth:    true
  fix_cgb:      true
  use_sun:      false
  cr_approximation: BGO
  use_eff_area_correction: true

################################ Bounds for the different sources ###################################
####### SAA: Amplitude and decay constant, CR: Constant and McIlwain normalization ##################
####### Point source: Amplitude, Earth/CGB fixec: Amplitude, Earth/CGB free: Amplitude, #############
############################ index1, index2 and break energy#########################################
priors:
  saa:
    norm:
      prior: log_uniform
      bounds: [1, 1.0e+4]
      gaussian: [null, null]
    decay:
      prior: log_uniform
      bounds: [1.0e-5, 1.0e-1]
      gaussian: [null, null]
  cr:
    const:
      prior: log_uniform
      bounds: [1.0e-1, 1.0e+2]
      gaussian: [null, null]
    norm:
      prior: log_uniform
      bounds: [0.1, 1.0e+2]
      gaussian: [null, null]
  earth:
    fixed:
      norm:
        prior: log_uniform
        bounds: [0.5e-2, 3.0e-2]
        gaussian: [null, null]
    free:
      norm:
        prior: log_uniform
        bounds: [1.0e-3, 1]
        gaussian: [null, null]
      alpha:
        prior: log_uniform
        bounds: [-8, -3]
        gaussian: [-5, 2]
      beta:
        prior: log_uniform
        bounds: [1.1, 1.9]
        gaussian: [1.72, 0.1]
      Eb:
        prior: log_uniform
        bounds: [20, 40]
        gaussian: [null, null]
  cgb:
    fixed:
      norm:
        prior: log_uniform
        bounds: [4.0e-2, 0.3]
        gaussian: [null, null]
    free:
      norm:
        prior: log_uniform
        bounds: [0.01, 0.5]
        gaussian: [null, null]
      alpha:
        prior: truncated_gaussian
        bounds: [0.5, 1.7]
        gaussian: [1.32, 0.1]
      beta:
        prior: truncated_gaussian
        bounds: [2.2, 3.1]
        gaussian: [2.88, 0.15]
      Eb:
        prior: log_uniform
        bounds: [27, 40]
        gaussian: [null, null]
  ps:
    fixed:
      pl:
        norm:
          prior: log_uniform
          bounds: [1.0e-4, 1.0e+9]
          gaussian: [null, null]
      bb:
        norm:
          prior: log_uniform
          bounds: [1.0e-4, 1.0e+9]
          gaussian: [null, null]
    free:
      pl:
        norm:
          prior: log_uniform
          bounds: [1.0e-1, 1.0e+5]
          gaussian: [null, null]
        index:
          prior: truncated_gaussian
          bounds: [0,4]
          gaussian: [2, 1]
      bb:
        norm:
          prior: log_uniform
          bounds: [1.0e-4, 10000]
          gaussian: [null, null]
        temp:
          prior: truncated_gaussian
          bounds: [0,50]
          gaussian: [10, 5]
  sun:
    norm:
        prior: log_uniform
        bounds: [1.0e-2, 1.0e+2]
        gaussian: [null, null]
    index:
        prior: truncated_gaussian
        bounds: [0.5,4]
        gaussian: [2, 1]
  gc:
    norm:
        prior: log_uniform
        bounds: [1.0e-3, 10]
        gaussian: [null, null]
  eff_area_correction:
      prior: truncated_gaussian
      bounds: [0.8,1.2]
      gaussian: [1, 0.1]

##################### Input for fit method ##########################################################
fit:
  method: 'multinest'
  multinest:
    num_live_points: 400
    constant_efficiency_mode: true
  use_numba: true

##################### Input for Result Export  ######################################################
export:
  save_cov_matrix: false
  save_ppc: true
  save_unbinned: false

############################### Input for plotting ##################################################
### bin_width to bin the data, change_time from MET to seconds since midnight, show residuals? ######
### show data?, show grb trigger times? if yes at which time ('20:57:03.000' format) and what name? #
### show ppc?, xlim and ylim (as list e.g. [0,100]), legend outside of the plot? ####################
plot:
  corner_plot:    true
  result_plot:    true
